/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package querybuilder;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testValidQueryFormat() {
        Query.Builder qb = new Query.Builder();

        String query = qb
                .select("*")
                .from("students")
                .where("grade >= 7")
                .orderBy("grade")
                .build();

        assertEquals("SELECT * FROM students WHERE grade >= 7 ORDER BY grade;", query);
    }

    @Test(expected = RuntimeException.class)
    public void testInvalidQueryFormat() {
        new Query.Builder()
                .select("*")
                .build();
    }
}
