/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package querybuilder;

import org.junit.Test;

import static org.junit.Assert.*;

public class QueryBuilderTest {
    @Test public void testValidQueryFormat() {
        Query.Builder qb = new Query.Builder();

        String query = qb
                .select("*")
                .from("students")
                .where("grade >= 7")
                .orderBy("grade")
                .build();

        assertEquals("SELECT * FROM students WHERE grade >= 7 ORDER BY grade;", query);
    }

    @Test public void testMultipleSelection() {
        Query.Builder qb = new Query.Builder();

        String query = qb
                .select("column1, column2")
                .from("students")
                .where("grade >= 7")
                .build();

        assertEquals("SELECT column1, column2 FROM students WHERE grade >= 7;", query);
    }

    @Test(expected = RuntimeException.class)
    public void testMissingClauses() {
        new Query.Builder()
                .select("*")
                .build();
    }

    @Test(expected = RuntimeException.class)
    public void testDuplicatedClauses() {
        new Query.Builder()
                .select("*")
                .from("students")
                .groupBy("grade")
                .from("anotherTable")
                .build();
    }

    @Test(expected = RuntimeException.class)
    public void testInvalidColumn() {
        new Query.Builder()
                .select("*")
                .from("students")
                .groupBy("grade")
                .from("anotherTable")
                .build();
    }
}
